<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AsteroidsSim.Tools.MathFingerprint</RootNamespace>
    <AssemblyName>MathFingerprint</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../AsteroidsSim/AsteroidsSim.csproj" />
  </ItemGroup>

</Project>
