using System;
using System.Collections.Generic;
using AsteroidsSim.Math;

namespace AsteroidsSim.Fracture;

/// <summary>
/// Builds a fracturable body: Voronoi tessellation, bond detection, the structure authoring layer,
/// the material bake, surface flags and shared-vertex grouping. A transcription of the prototype's
/// <c>addBody</c> / <c>applyStructure</c>.
/// </summary>
/// <remarks>
/// <para><b>RNG order is part of the contract.</b> The generator is consumed in exactly this
/// sequence: the outline ring (by the caller, via <see cref="MakeBlob"/>), then two draws per
/// tessellation grid point <i>including the points that are rejected</i> in a y-then-x scan, then
/// one draw for the body's grain axis (taken even when anisotropy is zero), then one Weibull draw
/// per bond. Change any of that and the bodies differ, which is a desync under lockstep and an
/// invalid comparison against the reference implementation.</para>
///
/// <para><b>Body creation order is likewise part of the contract</b> — bodies share one RNG stream,
/// so the order in which a scene is built decides what every body in it looks like.</para>
/// </remarks>
public static class BodyBuilder
{
    private const double MinCellArea = 12.0;
    private const double MinSharedEdge = 1.5;

    /// <summary>
    /// The prototype's <c>makeBlob</c>: a convex hull over a jittered ellipse ring. Consumes
    /// <paramref name="n"/> draws.
    /// </summary>
    /// <remarks>
    /// The ring angles go through <see cref="SimMath"/>, i.e. single precision, because the
    /// deterministic contract forbids the platform's double-precision trig. The reference
    /// implementation is JavaScript and therefore used double here, so an outline generated by this
    /// method differs from the reference in roughly the seventh digit — enough to move the convex
    /// hull and, through it, the whole tessellation. Equivalence tests therefore inject the outline
    /// explicitly (see <see cref="AddBody"/>) so that the tessellation itself is compared on
    /// identical input; this method is production code, not the comparison path.
    /// </remarks>
    public static List<Vec2d> MakeBlob(ref ProtoRng rng,
        double cx, double cy, double rx, double ry, double wob = 0.12, int n = 20)
    {
        var ring = new List<Vec2d>(n);
        for (int k = 0; k < n; k++)
        {
            float a = SimMath.TwoPI * k / n;
            double r = 1 + rng.Range(-wob, wob);
            SimMath.SinCos(a, out float sa, out float ca);
            ring.Add(new Vec2d(cx + ca * rx * r, cy + sa * ry * r));
        }
        return Geometry2D.ConvexHull(ring);
    }

    /// <summary>
    /// Tessellates <paramref name="outline"/> and appends the resulting body to
    /// <paramref name="s"/>. <paramref name="member"/> optionally carves the shape — rejected seeds
    /// still take part in the clipping ("phantom seeds"), without which a carved shape comes out as
    /// its bounding box.
    /// </summary>
    public static void AddBody(SimState s, ref ProtoRng rng, in SimTuning tune,
        List<Vec2d> outline, float velX, float velY, float omega,
        in Material material, float grain, Func<Vec2d, bool>? member = null)
    {
        var mp = new MaterialProps(material, tune);
        double step = System.Math.Sqrt(grain);
        Geometry2D.BBox(outline, out double minX, out double minY, out double maxX, out double maxY);

        // ── seeds ────────────────────────────────────────────────────────────
        var seedP = new List<Vec2d>();
        var seedReal = new List<bool>();
        for (double y = minY - step; y < maxY + step; y += step)
            for (double x = minX - step; x < maxX + step; x += step)
            {
                // Both draws happen for every grid point, before the accept test.
                double jx = rng.Range(-step * 0.34, step * 0.34);
                double jy = rng.Range(-step * 0.34, step * 0.34);
                var p = new Vec2d(x + jx, y + jy);
                bool inO = Geometry2D.PointInPoly(p, outline);
                bool real = inO && (member == null || member(p));
                if (real) { seedP.Add(p); seedReal.Add(true); }
                else if (member != null && inO) { seedP.Add(p); seedReal.Add(false); }
            }
        bool anyReal = false;
        for (int i = 0; i < seedReal.Count; i++) if (seedReal[i]) { anyReal = true; break; }
        if (!anyReal) { seedP.Add(Geometry2D.Centroid(outline)); seedReal.Add(true); }

        // ── Voronoi cells ────────────────────────────────────────────────────
        var rawPoly = new List<List<Vec2d>>();
        var rawCent = new List<Vec2d>();
        var rawArea = new List<double>();

        var work = new List<Vec2d>();
        var swap = new List<Vec2d>();

        for (int si = 0; si < seedP.Count; si++)
        {
            if (!seedReal[si]) continue;
            Vec2d sd = seedP[si];

            work.Clear();
            work.AddRange(outline);

            for (int ti = 0; ti < seedP.Count; ti++)
            {
                if (ti == si) continue;                       // the prototype compares by identity
                Vec2d t = seedP[ti];
                double mx = (sd.X + t.X) / 2, my = (sd.Y + t.Y) / 2;
                double nx = sd.X - t.X, ny = sd.Y - t.Y;
                double L = System.Math.Sqrt(nx * nx + ny * ny);
                if (L < 1e-6) continue;
                nx /= L; ny /= L;

                // BIT-SAFE SKIP. ClipHalf leaves a polygon untouched when every vertex is strictly
                // inside the half-plane, so skipping such a clip is identical to performing it —
                // not an approximation. This is what takes construction off O(seeds^2) in practice.
                if (!HalfPlaneCanCut(work, mx, my, nx, ny)) continue;

                Geometry2D.ClipHalf(work, new Vec2d(mx, my), new Vec2d(nx, ny), swap);
                (work, swap) = (swap, work);
                if (work.Count < 3) break;
            }

            if (work.Count < 3) continue;
            var poly = new List<Vec2d>(work);
            if (Geometry2D.Area(poly) < 0) poly.Reverse();
            double A = System.Math.Abs(Geometry2D.Area(poly));
            if (A < MinCellArea) continue;
            rawPoly.Add(poly);
            rawCent.Add(Geometry2D.Centroid(poly));
            rawArea.Add(A);
        }

        if (rawPoly.Count == 0) return;

        // ── body frame ───────────────────────────────────────────────────────
        double M = 0, cx = 0, cy = 0;
        for (int i = 0; i < rawPoly.Count; i++)
        {
            double m = rawArea[i] * mp.Rho;
            M += m; cx += rawCent[i].X * m; cy += rawCent[i].Y * m;
        }
        cx /= M; cy /= M;

        int bi = s.BodyCount;
        s.EnsureBodies(bi + 1);
        s.BodyX[bi] = (float)cx; s.BodyY[bi] = (float)cy; s.BodyRot[bi] = 0f;
        s.BodyVx[bi] = velX; s.BodyVy[bi] = velY; s.BodyW[bi] = omega;
        s.BodyWPrev[bi] = omega; s.BodyAlpha[bi] = 0f;
        s.BodyRho[bi] = mp.Rho; s.BodyCpx[bi] = mp.Cpx; s.BodyChi[bi] = mp.Chi;
        s.BodyVCrit[bi] = mp.VCrit; s.BodyDuct[bi] = mp.Duct;
        s.BodyCellSize[bi] = (float)step;
        s.BodyPlast[bi] = 0f; s.BodyEulL[bi] = 0f;
        s.BodyCount = bi + 1;

        bool solo = rawPoly.Count == 1;   // built as one cell: a legitimate pebble, never dust
        int cellStart = s.CellCount;
        double bodyI = 0;

        s.EnsureCells(cellStart + rawPoly.Count);
        for (int i = 0; i < rawPoly.Count; i++)
        {
            var poly = rawPoly[i];
            Vec2d cent = rawCent[i];
            double rx = cent.X - cx, ry = cent.Y - cy;
            double m = rawArea[i] * mp.Rho;
            double Ic = Geometry2D.PolyInertia(poly, cent) * mp.Rho;
            bodyI += Ic + m * (rx * rx + ry * ry);

            double rad2 = 0;
            for (int v = 0; v < poly.Count; v++)
            {
                double dx = poly[v].X - cent.X, dy = poly[v].Y - cent.Y;
                double rr = dx * dx + dy * dy;
                if (rr > rad2) rad2 = rr;
            }

            int ci = cellStart + i;
            s.EnsurePoly(s.PolyCount + poly.Count);
            s.PolyOff[ci] = s.PolyCount;
            s.PolyLen[ci] = poly.Count;
            for (int v = 0; v < poly.Count; v++)
            {
                s.PolyX[s.PolyCount] = (float)(poly[v].X - cent.X);
                s.PolyY[s.PolyCount] = (float)(poly[v].Y - cent.Y);
                s.PolyGroup[s.PolyCount] = -1;
                s.PolyCount++;
            }

            s.CellRx[ci] = (float)rx; s.CellRy[ci] = (float)ry;
            s.CellUx[ci] = 0f; s.CellUy[ci] = 0f; s.CellUth[ci] = 0f; s.CellPhi[ci] = 0f;
            s.CellDvx[ci] = 0f; s.CellDvy[ci] = 0f; s.CellDw[ci] = 0f;
            s.CellM[ci] = (float)m; s.CellIm[ci] = (float)(1.0 / m);
            s.CellIc[ci] = (float)Ic; s.CellIic[ci] = (float)(1.0 / Ic);
            s.CellArea[ci] = (float)rawArea[i];
            s.CellPerim[ci] = (float)Geometry2D.Perimeter(poly);
            s.CellRad[ci] = (float)System.Math.Sqrt(rad2);
            s.CellBody[ci] = bi;
            s.CellDead[ci] = false; s.CellCracked[ci] = false;
            s.CellSolo[ci] = solo; s.CellSurf[ci] = false;
            s.CellTouch[ci] = int.MinValue; s.CellBorn[ci] = int.MinValue; s.CellDeepN[ci] = 0;
            s.CellRotStamp[ci] = -1;
        }
        s.CellCount = cellStart + rawPoly.Count;
        s.BodyI[bi] = (float)bodyI;
        s.BodyM[bi] = (float)M;

        // ── bonds: cells sharing a Voronoi edge ──────────────────────────────
        int bondStart = s.BondCount;
        int n2 = rawPoly.Count;
        for (int i = 0; i < n2; i++)
            for (int j = i + 1; j < n2; j++)
            {
                int ca = cellStart + i, cb = cellStart + j;

                // BIT-SAFE SKIP: SegOverlap returns 0 for every edge pair of two cells whose
                // bounding circles do not touch, so the bond would not have been created.
                double ddx = s.CellRx[cb] - s.CellRx[ca], ddy = s.CellRy[cb] - s.CellRy[ca];
                double rsum = s.CellRad[ca] + s.CellRad[cb] + 1.0;
                if (ddx * ddx + ddy * ddy > rsum * rsum) continue;

                var pa = rawPoly[i]; var pb = rawPoly[j];
                Vec2d oa = new(s.CellRx[ca], s.CellRy[ca]);
                Vec2d ob = new(s.CellRx[cb], s.CellRy[cb]);

                double sh = 0, mx = 0, my = 0; int cnt = 0;
                for (int a = 0; a < pa.Count; a++)
                {
                    Vec2d a0 = new(pa[a].X - rawCent[i].X + oa.X, pa[a].Y - rawCent[i].Y + oa.Y);
                    Vec2d a1n = pa[(a + 1) % pa.Count];
                    Vec2d a1 = new(a1n.X - rawCent[i].X + oa.X, a1n.Y - rawCent[i].Y + oa.Y);
                    for (int z = 0; z < pb.Count; z++)
                    {
                        Vec2d b0 = new(pb[z].X - rawCent[j].X + ob.X, pb[z].Y - rawCent[j].Y + ob.Y);
                        Vec2d b1n = pb[(z + 1) % pb.Count];
                        Vec2d b1 = new(b1n.X - rawCent[j].X + ob.X, b1n.Y - rawCent[j].Y + ob.Y);
                        double ov = Geometry2D.SegOverlap(a0, a1, b0, b1);
                        if (ov > 0)
                        {
                            sh += ov;
                            mx += (a0.X + a1.X) / 2; my += (a0.Y + a1.Y) / 2;
                            cnt++;
                        }
                    }
                }
                if (sh <= MinSharedEdge || cnt == 0) continue;
                mx /= cnt; my /= cnt;

                double nx = s.CellRx[cb] - s.CellRx[ca], ny = s.CellRy[cb] - s.CellRy[ca];
                double L = System.Math.Sqrt(nx * nx + ny * ny);
                if (L == 0) L = 1;
                nx /= L; ny /= L;

                double Lb = System.Math.Max(1.0, sh);
                double k0 = mp.Rho * mp.Cpx * mp.Cpx * (Lb / step);

                int bk = s.BondCount;
                s.EnsureBonds(bk + 1);
                s.BondA[bk] = ca; s.BondB[bk] = cb;
                s.BondLen[bk] = (float)sh;
                s.BondStr[bk] = 1f;
                s.BondK0[bk] = (float)k0;
                s.BondKa0[bk] = (float)(k0 * Lb * Lb / 12.0);
                s.BondS0[bk] = 0f; s.BondSy0[bk] = 0f;
                s.BondRax[bk] = (float)(mx - s.CellRx[ca]);
                s.BondRay[bk] = (float)(my - s.CellRy[ca]);
                s.BondRbx[bk] = (float)(mx - s.CellRx[cb]);
                s.BondRby[bk] = (float)(my - s.CellRy[cb]);
                s.BondNx[bk] = (float)nx; s.BondNy[bk] = (float)ny;
                s.BondSn[bk] = 0f; s.BondSt[bk] = 0f; s.BondSa[bk] = 0f;
                s.BondPn[bk] = 0f; s.BondPt[bk] = 0f; s.BondPa[bk] = 0f; s.BondPTot[bk] = 0f;
                s.BondDmg[bk] = 0f; s.BondLmax[bk] = 0f; s.BondRate[bk] = 0f;
                s.BondBroken[bk] = false; s.BondMode[bk] = 0;
                s.BondCount = bk + 1;
            }

        ApplyStructure(s, ref rng, tune, bondStart, s.BondCount);

        // Peak and yield stretch bake AFTER structure: the authoring layer scales STRENGTH, never
        // stiffness — heterogeneous stiffness would make the wave field heterogeneous too.
        for (int k = bondStart; k < s.BondCount; k++)
        {
            s.BondS0[k] = (float)(mp.VCrit * step / mp.Cpx) * s.BondStr[k];
            s.BondSy0[k] = s.BondS0[k] * mp.Yield;
        }

        // ── surface cells ────────────────────────────────────────────────────
        // A cell whose bonded edge length falls well short of its perimeter has faces nothing is
        // glued to. Both the outline and carved interior boundaries register. Cracks may only
        // SEPARATE at a surface, so this is where "surface" is defined.
        {
            var acc = new double[rawPoly.Count];
            for (int k = bondStart; k < s.BondCount; k++)
            {
                acc[s.BondA[k] - cellStart] += s.BondLen[k];
                acc[s.BondB[k] - cellStart] += s.BondLen[k];
            }
            for (int i = 0; i < rawPoly.Count; i++)
                s.CellSurf[cellStart + i] = acc[i] < s.CellPerim[cellStart + i] * 0.75;
        }

        BuildVertexGroups(s, cellStart, s.CellCount);
        RebuildMembership(s);
        s.Reindex();
    }

    /// <summary>
    /// True when the half-plane could remove at least one vertex. Used only to skip clips that
    /// provably do nothing — see the call site.
    /// </summary>
    private static bool HalfPlaneCanCut(List<Vec2d> poly, double px, double py, double nx, double ny)
    {
        for (int i = 0; i < poly.Count; i++)
        {
            double d = (poly[i].X - px) * nx + (poly[i].Y - py) * ny;
            if (d < 0) return true;
        }
        return false;
    }

    /// <summary>
    /// The structure authoring layer. Writes exactly one number per bond — <c>BondStr</c> — from
    /// composable patterns; the solver never learns how it was produced, and fragments inherit it
    /// for free because each bond carries its own value through splitting.
    /// </summary>
    private static void ApplyStructure(SimState s, ref ProtoRng rng, in SimTuning tune,
        int bondStart, int bondEnd)
    {
        if (bondEnd <= bondStart) return;

        // Drawn unconditionally when the grain is not locked, even at zero anisotropy — the
        // prototype consumes it either way, and the stream position is part of the contract.
        double g = tune.GrainLock ? tune.GrainAngle : rng.Range(0, System.Math.PI);

        // neighbour counts, for the surface-flaw pattern
        var nb = new Dictionary<int, int>();
        for (int k = bondStart; k < bondEnd; k++)
        {
            nb.TryGetValue(s.BondA[k], out int va); nb[s.BondA[k]] = va + 1;
            nb.TryGetValue(s.BondB[k], out int vb); nb[s.BondB[k]] = vb + 1;
        }

        float m = tune.WeibullM;
        float med = m > 0 ? SimMath.Pow(0.6931471805599453f, 1f / m) : 1f;

        for (int k = bondStart; k < bondEnd; k++)
        {
            float str = 1f;

            // Weibull scatter, median-normalised to 1. Weakest-link nucleation: this is what turns
            // "the whole shocked region crosses threshold together" into cracks that start
            // somewhere. One draw per bond, in bond order.
            if (m > 0)
            {
                double u = System.Math.Max(1e-9, 1.0 - rng.NextDouble());
                str *= SimMath.Pow(-SimMath.Log((float)u), 1f / m) / med;
            }

            // Bedding-plane anisotropy. A bond along the grain is stronger, across it weaker;
            // doubled angle because a bedding plane is an axis.
            if (tune.Aniso > 0)
            {
                int a = s.BondA[k], b = s.BondB[k];
                float ba = SimMath.Atan2(s.CellRy[b] - s.CellRy[a], s.CellRx[b] - s.CellRx[a]);
                str *= SimMath.Max(0.05f, 1f + tune.Aniso * SimMath.Cos(2f * (ba - (float)g)));
            }

            // Surface flaws: bonds whose cells sit at the boundary are weaker. Real brittle solids
            // crack from surface defects, and this is what lets glass initiate at all.
            if (tune.SurfFlaw > 0)
            {
                nb.TryGetValue(s.BondA[k], out int na);
                nb.TryGetValue(s.BondB[k], out int nbb);
                if (System.Math.Min(na, nbb) < 4) str *= 1f - tune.SurfFlaw;
            }

            s.BondStr[k] = SimMath.Clamp(str, 0.05f, 3f);
        }
    }

    /// <summary>
    /// Groups coincident polygon vertices. A bond is a shared side, so the two cells' copies of it
    /// must never move apart; the skinning in the renderer/narrow phase places every copy at the
    /// average of where the sharing cells put it, which makes a gap unrepresentable.
    /// </summary>
    private static void BuildVertexGroups(SimState s, int cellStart, int cellEnd)
    {
        const double Q = 2.0;            // 0.5 px buckets
        const double Tol = 0.35;
        var hash = new Dictionary<long, List<int>>();
        var posX = new List<double>();
        var posY = new List<double>();
        var members = new List<(int cell, int vert)>();
        var groupStartLocal = s.GrpCount;

        // group id -> member list, kept as parallel lists while building
        var grpMembers = new List<List<(int cell, int vert)>>();

        for (int ci = cellStart; ci < cellEnd; ci++)
        {
            int off = s.PolyOff[ci], len = s.PolyLen[ci];
            for (int v = 0; v < len; v++)
            {
                double px = s.CellRx[ci] + s.PolyX[off + v];
                double py = s.CellRy[ci] + s.PolyY[off + v];
                long gx = (long)System.Math.Round(px * Q);
                long gy = (long)System.Math.Round(py * Q);

                int found = -1;
                for (long dx = -1; dx <= 1 && found < 0; dx++)
                    for (long dy = -1; dy <= 1 && found < 0; dy++)
                    {
                        long key = (gx + dx) * 100003L + (gy + dy);
                        if (!hash.TryGetValue(key, out var bucket)) continue;
                        for (int bidx = 0; bidx < bucket.Count; bidx++)
                        {
                            int cand = bucket[bidx];
                            if (System.Math.Abs(posX[cand] - px) < Tol &&
                                System.Math.Abs(posY[cand] - py) < Tol)
                            { found = cand; break; }
                        }
                    }

                if (found < 0)
                {
                    found = posX.Count;
                    posX.Add(px); posY.Add(py);
                    grpMembers.Add(new List<(int, int)>());
                    long key = gx * 100003L + gy;
                    if (!hash.TryGetValue(key, out var bucket)) { bucket = new List<int>(); hash[key] = bucket; }
                    bucket.Add(found);
                }

                grpMembers[found].Add((ci, v));
                s.PolyGroup[off + v] = groupStartLocal + found;
            }
        }

        s.EnsureGroups(groupStartLocal + grpMembers.Count);
        int memberOff = s.GrpMemberCount;
        int totalMembers = 0;
        for (int i = 0; i < grpMembers.Count; i++) totalMembers += grpMembers[i].Count;
        s.EnsureGroupMembers(memberOff + totalMembers);

        for (int i = 0; i < grpMembers.Count; i++)
        {
            int gid = groupStartLocal + i;
            s.GrpOff[gid] = memberOff;
            s.GrpLen[gid] = grpMembers[i].Count;
            for (int j = 0; j < grpMembers[i].Count; j++)
            {
                s.GrpCell[memberOff] = grpMembers[i][j].cell;
                s.GrpVert[memberOff] = grpMembers[i][j].vert;
                memberOff++;
            }
        }
        s.GrpCount = groupStartLocal + grpMembers.Count;
        s.GrpMemberCount = memberOff;
        _ = members;
    }

    /// <summary>
    /// Rebuilds the per-body cell lists by scanning cells in index order, so membership order — and
    /// therefore every per-body loop — is a pure function of cell indices.
    /// </summary>
    public static void RebuildMembership(SimState s)
    {
        for (int b = 0; b < s.BodyCount; b++) s.BodyCellLen[b] = 0;
        for (int c = 0; c < s.CellCount; c++)
        {
            if (s.CellDead[c]) continue;
            int b = s.CellBody[c];
            if (b >= 0 && b < s.BodyCount) s.BodyCellLen[b]++;
        }
        int off = 0;
        for (int b = 0; b < s.BodyCount; b++) { s.BodyCellOff[b] = off; off += s.BodyCellLen[b]; }
        s.BodyCellsCount = off;
        s.EnsureBodyCells(System.Math.Max(1, off));

        for (int b = 0; b < s.BodyCount; b++) s.BodyCellLen[b] = 0;
        for (int c = 0; c < s.CellCount; c++)
        {
            if (s.CellDead[c]) continue;
            int b = s.CellBody[c];
            if (b < 0 || b >= s.BodyCount) continue;
            s.BodyCells[s.BodyCellOff[b] + s.BodyCellLen[b]++] = c;
        }
    }
}
